#### NumPy -- > Numerical Python

Advantage in Numpy Arrays
1. Allows several mathematical operations
2. Faster Operations

In [1]:
#importing libraries
import numpy as np

#### List vs NumPy timetaken

In [5]:
from time import process_time

##### Time taken by a list

In [6]:
python_list =[i for i in range(10000)]

start_time = process_time()

python_list = [i+5 for i in python_list]

end_time = process_time()

print(end_time - start_time)

0.0


In [7]:
from time import process_time  # Import process_time from the time module

# Initialize the list with numbers from 0 to 9999
python_list = [i for i in range(10000)]

# Record the start time
start_time = process_time()

# Increment each element in the list by 5
python_list = [i + 5 for i in python_list]

# Record the end time
end_time = process_time()

# Print the time taken for the operation
print(end_time - start_time)


0.0


In [8]:
from time import time  # Import time for wall-clock time

# Initialize the list with numbers from 0 to 9999
python_list = [i for i in range(10000)]

# Record the start time
start_time = time()

# Increment each element in the list by 5
python_list = [i + 5 for i in python_list]

# Record the end time
end_time = time()

# Print the time taken for the operation
print(end_time - start_time)


0.0010082721710205078


In [11]:
np_array = np.array([i for i in range(10000)])

start_time = time()

#adding values
np_array += 5 

end_time = time()

print(end_time - start_time)

0.012342453002929688


### Numpy Arrays

In [12]:
#lisst
list1 = [1,2,3,4,5]
print(list1)
print(type(list1))

[1, 2, 3, 4, 5]
<class 'list'>


In [14]:
np_array = np.array([1,2,3,4,5])
print(np_array)
print(type(np_array))

[1 2 3 4 5]
<class 'numpy.ndarray'>


In [15]:
# creating a one dimensional array
a = np.array([1,2,3,4])
print(a)

[1 2 3 4]


In [16]:
a.shape -->#rows and columns in array

(4,)

In [19]:
b = np.array([(5,6,7,8),(1,2,3,4)])
print(b)

[[5 6 7 8]
 [1 2 3 4]]


In [20]:
b.shape -->#here we can see it has 2 rows and 4 columns

(2, 4)

In [22]:
c = np.array([(1,2,3,4),(5,6,7,8)],dtype=float) # here we are changing to float
print(c)

[[1. 2. 3. 4.]
 [5. 6. 7. 8.]]


##### Initial placeholder in numpy array

initialize array in some cases

In [23]:
#create a numpy array of Zeros
x = np.zeros((4,5))
print(x)

[[0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0.]]


In [25]:
# create a numpy array of ones
y = np.ones((4,5))
print(y)

[[1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1.]]


In [26]:
#array of a particular values
z = np.full((5,4),5) #here i need 5 columns and 4 rows of 5 number
print(z)

[[5 5 5 5]
 [5 5 5 5]
 [5 5 5 5]
 [5 5 5 5]
 [5 5 5 5]]


In [28]:
#create a identiy matrix --> has same number of rows and columns
a = np.eye(5)
print(a)

[[1. 0. 0. 0. 0.]
 [0. 1. 0. 0. 0.]
 [0. 0. 1. 0. 0.]
 [0. 0. 0. 1. 0.]
 [0. 0. 0. 0. 1.]]


In [29]:
#create a numpy array with random values
b = np.random.random((3,4))
print(b)

[[0.35048032 0.54182313 0.21517477 0.63375994]
 [0.54225445 0.87009825 0.76833179 0.03790691]
 [0.44348088 0.90640126 0.05733056 0.82861621]]


In [30]:
#create a numpy array with random integer values within a specific range
c = np.random.randint(10,100,(3,5))
print(c)


[[14 40 56 54 13]
 [85 97 49 13 87]
 [35 15 97 52 67]]


In [39]:
#array of evenly spaced values  -> specifying the number of values required
d = np.linspace(10,30,5)
print(d)

[10. 15. 20. 25. 30.]


In [32]:
#array of evenly spaced values -> specifying the steps
e = np.arange(10,30,5)
print(e)

[10 15 20 25]


In [41]:
#convert a list to an numpy array
list2 =[10,20,30,40,50]
np_array = np.asarray(list2)
print(np_array)
type(np_array)

[10 20 30 40 50]


numpy.ndarray

### Analysing the numpy array

In [42]:
c = np.random.randint(10,90,(5,5))
print(c)

[[71 47 66 11 78]
 [22 26 61 83 18]
 [16 37 23 58 48]
 [59 79 85 60 23]
 [32 34 15 12 12]]


In [43]:
#array dimension
print(c.shape)

(5, 5)


In [44]:
#number of dimension -->its rows and columns so it is showing 2
print(c.ndim)

2


In [45]:
#number of elements in array
print(c.size)

25


In [46]:
#datatype of the values in the array
print(c.dtype)

int32


#### Mathematical operations on a np array

In [47]:
list1 =[1,2,3,4,5]
list2 = [6,7,8,9,10]
print(list1 + list2)  # this concatenate or joins two list

[1, 2, 3, 4, 5, 6, 7, 8, 9, 10]


In [48]:
a = np.random.randint(0,10,(3,3))
b = np.random.randint(10,20,(3,3))

print(a)
print(b)


[[5 2 0]
 [8 1 2]
 [5 6 6]]
[[15 12 18]
 [19 10 19]
 [10 14 18]]


In [49]:
print(a+b) # in the case of list it joined or concatenated but here we can see the 'a' and 'b' values are added

[[20 14 18]
 [27 11 21]
 [15 20 24]]


In [50]:
print(a-b)
print(a*b)
print(a/b)

[[-10 -10 -18]
 [-11  -9 -17]
 [ -5  -8 -12]]
[[ 75  24   0]
 [152  10  38]
 [ 50  84 108]]
[[0.33333333 0.16666667 0.        ]
 [0.42105263 0.1        0.10526316]
 [0.5        0.42857143 0.33333333]]


In [51]:
a = np.random.randint(0,10,(3,3))
b = np.random.randint(10,20,(3,3))

print(a)
print(b)


[[1 7 3]
 [7 2 7]
 [2 7 6]]
[[16 11 17]
 [16 14 19]
 [12 18 12]]


In [52]:
print(np.add(a,b))
print(np.subtract(a,b))
print(np.multiply(a,b))
print(np.divide(a,b))

[[17 18 20]
 [23 16 26]
 [14 25 18]]
[[-15  -4 -14]
 [ -9 -12 -12]
 [-10 -11  -6]]
[[ 16  77  51]
 [112  28 133]
 [ 24 126  72]]
[[0.0625     0.63636364 0.17647059]
 [0.4375     0.14285714 0.36842105]
 [0.16666667 0.38888889 0.5       ]]


#### array manipulation

In [53]:
array = np.random.randint(0,10,(2,3))
print(array)
print(array.shape)

[[7 7 3]
 [3 1 3]]
(2, 3)


In [57]:
#transpose
trans = np.transpose(array)
print(trans)
print("shape is :",trans.shape)

[[7 3]
 [7 1]
 [3 3]]
shape is : (3, 2)


In [58]:
trans2 = array.T
print(trans2)
print("shape is:",trans2.shape)

[[7 3]
 [7 1]
 [3 3]]
shape is: (3, 2)


#### reshaping array

In [59]:

a = np.random.randint(0,10,(2,3))
print(a)
print(a.shape)

[[2 0 6]
 [5 9 4]]
(2, 3)


In [60]:
b = a.reshape(3,2)
print(b)
print(b.shape)

[[2 0]
 [6 5]
 [9 4]]
(3, 2)
